In [1]:
import pandas as pd

In [31]:
Data = '../data/processed/full_data.csv'

In [2]:
full_df = pd.read_csv(Data)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
full_df.head(50)

,msno,is_churn,city,bd,gender,registered_via,registration_init_time,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mode_plan_list_price,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_ex_latest_mean_discount_amount,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,hist_ex_latest_mode_is_auto_renew,recent_autorenew_intent_trend,hist_expiration_recency_days,payment_toggle_state_flips,payment_elasticity_vector,replenishment_consistency_variance,payment_discount_amount,payment_discount_ratio,is_promo_tier_subscriber,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,jan_pre_w3_num_unq,jan_pre_w3_days_active,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,dec_raw_log_rows,jan_raw_log_rows,feb_raw_log_rows,total_songs_w0,total_secs_w0,num_100_w0,num_unq_w0,total_songs_w1,total_secs_w1,num_100_w1,num_unq_w1,total_songs_w2,total_secs_w2,num_100_w2,num_unq_w2,total_songs_w3,total_secs_w3,num_100_w3,num_unq_w3,active_days_w0,active_days_w1,active_days_w2,active_days_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,last_3d_raw_rows,coefficient_of_daily_variation_feb,max_single_day_songs_w0,inactivity_chunkiness_index_feb,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,trend_3m_monthly_velocity_total_secs,trend_3m_monthly_velocity_num_unq,trend_3m_monthly_velocity_num_100,trend_3m_monthly_velocity_days_active,trend_3m_monthly_velocity_repeat_songs,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,feb_daily_session_density,feb_daily_variety_density,last_3d_micro_session_density,raw_last_3d_daily_songs,raw_w0_daily_songs,raw_last_3d_active_days,raw_w0_active_days,raw_feb_log_rows,feb_true_active_days,true_relative_performance_ratio_complete,active_day_engagement_density_feb,extreme_stream_compression_ratio_w0,inter_auto_renew_x_fading_3d_stats,inter_auto_renew_x_last_3d_low_unq,inter_auto_renew_x_w0_structural_slump,inter_auto_renew_x_multi_window_decay,inter_auto_renew_x_engagement_desert,inter_auto_renew_x_promo_wall_cross,inter_auto_renew_x_ghost_billing_disconnect,inter_loyal_x_low_3d_unq,inter_loyal_x_low_tier_payer,inter_autorenew_x_desert_payer,inter_autorenew_x_low_tier_payer,is_legacy_ghost,ghost_group_base_rate,time_active
0,ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=,1,5.0,28.0,male,3.0,20131223.0,0.0,149.0,0.0,6.000000,149.00000,29.800000,24.200000,-119.200000,30.0,149.0,149.0,30.0,0.0,0.0,1.0,6.0,1.0,700.0,0.0,0.166667,31,1.0,-1.0,-30.0,1.0,0.000000,13.500000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12472.612,43.0,11.0,4.0,1.0,44.0,46.0,103.0,1.0,57.0,0.0,0.0,1.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,12472.612,103.0,46.0,1.0,1.0,0.000000,0.0,30.0,0.0,0.0000,0.0,0.0,0.0,103.0,12472.6120,1.0,46.0,57.0,103.0,12472.612,1.0,46.0,57.0,0.0,0.000,0.0,0.0,6236.3060,23.0,22.0,0.5,28.5,0.0,0.000,0.0,0.0,103.000000,12472.612000,103.000000,12472.612000,0.333333,0.000000,1.0,46.000000,1.0,34.333333,0.000000,1.0,0.0,1.0,1.0,-2.000000,46.000000,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
1,f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=,1,13.0,20.0,male,3.0,20131223.0,30.0,149.0,149.0,24.250000,111.75000,111.750000,31.250000,0.000000,30.0,180.0,180.0,30.0,0.0,0.0,0.0,5.0,1.0,344.0,18.0,0.000000,38,0.0,0.0,-12.0,0.0,1.208054,0.000000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18474.223,16.0,5.0,2.0,3.0,69.0,68.0,95.0,9.0,27.0,0.0,0.0,9.0,35.0,7501.249,28.0,27.0,22.0,3907.550,13.0,18.0,2.0,34.743,0.0,1.0,0.0,0.000,0.0,0.0,4.0,2.0,1.0,0.0,7030.681,36.0,22.0,2.0,2.0,0.585891,16.0,12.0,0.0,0.0000,0.0,0.0,0.0,95.0,18474.2230,9.0,68.0,27.0,95.0,18474.223,9.0,68.0,27.0,0.0,0.000,0.0,0.0,9237.1115,34.0,34.5,4.5,13.5,13.0,3593.699,15.0,9.0,18.000000,3515.340500,9.250000,1640.028250,0.666667,6.500000,1.0,7.555556,1.0,12.000000,5.000000,2.0,4.0,9.0,9.0,-2.000000,7.555556,0.457143,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
2,zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=,1,13.0,18.0,male,3.0,20131227.0,30.0,149.0,149.0,30.000000,149.00000,149.000000,30.294117,0.000000,30.0,149.0,149.0,36.0,0.0,0.0,0.0,18.0,1.0,530.0,29.0,0.000000,38,0.0,0.0,-7.0,0.0,1.000000,55.954594,0.0,0.0,0.0,101482.189,345.0,56.0,27.0,27.0,335.0,685.0,790.0,18.0,105.0,93466.669,264.0,49.0,53.0,40.0,279.0,542.0,685.0,21.0,143.0,517.0,18.0,68146.893,182.0,53.0,26.0,18.0,239.0,407.0,518.0,20.0,111.0,18.0,21.0,20.0,144.0,12337.889,46.0,85.0,57.0,10498.400,40.0,45.0,148.0,23023.211,75.0,139.0,127.0,16922.525,53.0,105.0,4.0,2.0,7.0,7.0,10287.723,80.0,58.0,3.0,3.0,0.727179,72.0,5.0,737.5,97474.4290,19.5,613.5,124.0,-219.5,-29327.5360,0.5,-206.5,-13.0,-167.0,-25319.776,-1.0,-135.0,-32.0,-105.0,-8015.520,-143.0,38.0,-16667.6480,-139.0,-48.0,1.0,3.0,87.0,1839.489,6.0,40.0,26.666667,3429.241000,-9.333333,344.768750,1.000000,-7.253333,1.0,20.350000,1.0,26.666667,20.571429,3.0,4.0,20.0,20.0,0.856631,20.350000,0.500000,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
3,8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=,1,1.0,0.0,NaN,7.0,20140109.0,30.0,149.0,149.0,26.470589,149.00000,131.470580,337.588230,-17.529411,30.0,149.0,149.0,0.0,1.0,1.0,2.0,18.0,1.0,413.0,369.0,0.111111,41,1.0,0.0,369.0,0.0,1.000000,76.459140,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,0,0.0000,NaN
4,K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=,1,13.0,35.0,female,7.0,20140125.0,30.0,129.0,129.0,26.086956,124.21739,105.652176,182.608690,-18.565218,30.0,99.0,99.0,185.0,0.0,1.0,2.0,24.0,1.0,586.0,180.0,0.083333,41,1.0,0.0,-5.0,0.0,0.767442,26.512053,0.0,0.0,0.0,37836.665,44.0,11.0,9.0,3.0,131.0,183.0,198.0,14.0,15.0,968.371,2.0,1.0,0.0,1.0,2.0,5.0,6.0,1.0,1.0,5.0,1.0,45495.387,74.0,29.0,2.0,6.0,168.0,213.0,279.0,12.0,66.0,14.0,1.0,12.0,138.0,21082.800,79.0,115.0,83.0,16775.852,64.0,45.0,14.0,3349.438,13.0,13.0,0.0,0.000,0.0,0.0,5.0,3.0,2.0,0.0,4287.297,44.0,40.0,2.0,2.0,1.041051,90.0,7.0,102.0,19402.5180,7.5,94.0,8.0,177.0,26092.8690,4.5,119.0,58.0,273.0,44527.016,11.0,208.0,65.0,-192.0,-36868.294,-178.0,-14.0,3829.3610,15.0,18.5,-1.0,25.5,55.0,4306.948,15.0,70.0,22.000000,2143.648500,-5.600000,-2072.911500,0.666667,8.176471,1.0,17.750000,1.0,14.666667,19.714286,2.0,5.0,12.0,12.0,84.000000,17.750000,0.652174,0,0,0,0,0,0,0,0,1,0,1,0,0.0000,NaN
5,ibIHVYBqxGwrSExE63/omeDD99M5vYB3CN2HzkEY+eM=,1,22.0,0.0,NaN,3.0,20140126.0,30.0,149.0,149.0,28.473684,149.00000,141.157900,27.894737,-7.842105,30.0,149.0,149.0,27.0,0.0,1.0,1.0,20.0,1.0,682.0,13.0,0.050000,40,1.0,0.0,-14.0,0.0,1.000000,0.000000,0.0,0.0,0.0,38186.547,12.0,6.0,13.0,5.0,140.0,155.0,176.0,7.0,21.0,16939.815,16.0,3.0,2.0,4.0,57.0,75.0,82.0,7.0,7.0,75.0,7.0,69685.131,63.0,24.0,18.0,13.0,258.0,340.0,376.0,13.0,36.0,7.0,7.0,13.0,67.0,10948.307,36.0,57.0,115.0,19581.039,69.0,112.0,39.0,7400.338,26.0,30.0,91.0,17671.611,68.0,91.0,2.0,5.0,2.0,2.0,14083.836,64.0,50.0,2.0,2.0,0.870189,62.0,5.0,129.0,27563.1810,7.0,115.0,14.0,247.0,42121.9500,6.0,225.0,22.0,294.0,52745.316,6.0,265.0,29.0,-94.0,-21246.732,-80.0,-14.0,15749.2920,92.5,59.0,3.0,7.5,-48.0,-8632.732,-33.0,-55.0,32.000000,7041.918000,-1.500000,1567.764500,0.666667,4.642857,1.0,26.153846,1.0,21.333333,9.571429,2.0,2.0,13.0,13.0,4.526316,26.153846,0.925373,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
6,kVmM8X4iBPCOfK/m1l3KR7LjFoxD1EcKYCc76F5IAWw=,1,1.0,0.0,NaN,7.0,20140129.0,30.0,99.0,99.0,30.000000,99.00000,99.000000,30.714285,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,8.0,1.0,215.0,8.0,0.000000,41,1.0,0.0,-20.0,0.0,1.000000,0.000000,0.0,0.0,0.0,10101.114,1.0,0.0,0.0,0.0,47.0,47.0,48.0,1.0,1.0,4829.124,0.0,1.0,0.0,1.0,19.0,21.0,21.0,1.0,0.0,21.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,-1.000000,0.0,30.0,34.5,7465.1190,1.0,34.0,0.5,-34.5,-7465.1190,-1.0,-34.0,-0.5,-21.0,-4829.124,-1.0,-21.0,0.0,-27.0,-5271.990,-26.0,-1.0,-5050.5570,-23.5,-23.5,-0.5,-0.5,0.0,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-34.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1,1,1,1,1,0,0,0,0,1,1,0,0.0000,NaN
7,moRTKhKIDvb+C8ZHOgmaF4dXMLk0jOn65d7a8tQ2Eds=,1,9.0,28.0,female,3.0,20140202.0,410.0,1788.0,1788.0,410.000000,1788.00000,1788.000000,458.000000,0.000000,195.0,894.0,894.0,323.0,0.0,0.0,0.0,2.0,1.0,330.0,294.0,0.000000,38,0.0,0.0,-29.0,0.0,0.500000,0.000000,0.0,0.0,0.0,221228.068,69.0,21.0,15.0,14.0,851.0,658.0,970.0,26.0,312.0,268627.665,94.0,32.0,28.0,18.0,1048.0,741.0,1220.0,28.0,479.0,637.0,25.0,252772.439,49.0,11.0,12.0,9.0,981.0,601.0,1062.0,26.0,461.0,26.0,28.0,26.0,240.0,54920.797,231.0,167.0,330.0,74230.474,315.0,175.0,133.0,33604.213,129.0,88.0,229.0,62326.249,172.0,177.0,6.0,7.0,7.0,6.0,56846.492,278.0,98.0,3.0,3.0,0.791870,97.0,1.0,1095.0,244927.8665,27.0,699.5,395.5,-33.0,7844.5725,-1.0,-98.5,65.5,-158.0,-15855.226,-2.0,-140.0,-18.0,250.0,47399.597,83.0,167.0,15772.1855,-28.5,65.0,0.0,74.5,-90.0,-19309.677,-84.0,-8.0,92.666667,18948.830333,52.666667,9795.364167,1.000000,1.932692,1.0,23.115385,1.0,92.666667,34.285714,3.0,6.0,26.0,26.0,0.936069,23.115385,0.404167,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
8,dW/tPZMDh2Oz/ksduEctJbsz0MXw3kay/1AlZCq3EbI=,1,13.0,21.0,female,9.0,20140212.0,30.0,149.0,149.0,52.857143,243.14285,243.142850,69.428570,0.000000,30.0,149.0,149.0,59.0,0.0,0.0,0.0,8.0,1.0,341.0,50.0,0.000000,38,0.0,0.0,-9.0,0.0,1.000000,17.500000,0.0,0.0,0.0,109212.392,292.0,70.0,26.0,49.0,374.0,663.0,811.0,22.0,148.0,148005.774,367.0,64.0,31.0,52.0,516.0,894.0,1030.0,30.0,136.0,807.0,27.0,153234.568,211.0,49.0,26.0,39.0,580.0,817.0,905.0,21.0,88.0,22.0,30.0,21.0,166.0,31205.152,121.0,123.0,176.0,22001.378,66.0,169.0,421.0,74391.980,295.0,398.0,227.0,36664.389,137.0,209.0,6.0,5.0,6.0,6.0,755.821,6.0,5.0,1.0,1.0,0.797338,73.0,2.0,920.5,128609.0830,26.0,778.5,142.0,-15.5,24625.4850,-5.0,38.5,-54.0,-125.0,5228.794,-9.0,-77.0,-48.0,219.0,38793.382,231.0,-12.0,22011.0880,77.0,103.0,-0.5,-30.0,-10.0,9203.774,55.0,-46.0,6.000000,755.821000,-21.666667,-4445.037667,0.333333,-7.503726,1.0,38.904762,1.0,2.000000,23.714286,1.0,6.0,21.0,21.0,1.124031,38.904762,0.439759,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
9,otEcMhAX3mU4gumUSogqgteN3oaNmhdmTkoof2iRYEE=,1,13.0,0.0,NaN,7.0,20140228.0,30.0,149.0,149.0,28.636364,149.00000,142.227280,32.681820,-6.772728,30.0,149.0,149.0,60.0,0.0,1.0,0.0,23.0,2.0,744.0,33.0,0.000000,38,0.0,1.0,-27.0,1.0,1.000000,76.725490,0.0,0.0,0.0,84931.310,298.0,26.0,11.0,9.0,340.0,519.0,684.0,23.0,165.0,115509.132,1232.0,45.0,13.0,20.0,439.0,1329.0,1749.0,23.0,420.0,1263.0,21.0,70589.899,183.0,24.0,13.0,15.0,287.0,363.0,522.0,20.0,159.0,23.0,23.0,20.0,122.0,20673.748,88.0,72.0,69.0,11153.776,39.0,42.0,77.0,13075.409,58.0,37.0,215.0,18893.571,75.0,174.0,6.0,4.0,5.0,5.0,11226.447,118.0,104.0,2.0,2.0,1.023614,31.0,2.0,1216.5,100220.2210,23.0,924.0,292.5,-694.5,-29630.3220,-3.0,-561.0,-133.5,-1227.0,-44919.233,-3.0,-966.0,-261.0,1065.0,30577.822,810.0,255.0,-7170.7055,-78.0,-26.5,-1.5,-3.0,53.0,9519.973,49.0,30.0,59.000000,5613.223500,38.666667,2167.598667,0.666667,-25.507407,1.0,18.150000,1.0,39.333333,17.428571,2.0,6.0,20.0,20.0,0.653759,18.150000,0.254098,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
10,t5rqTxCnG7s5VBgEfdkQCezv5KBK7+DMujNibYgylrs=,1,13.0,0.0,NaN,9.0,20140307.0,30.0,149.0,149.0,30.000000,149.00000,149.000000,30.000000,0.000000,30.0,149.0,149.0,30.0,0.0,0.0,0.0,13.0,1.0,480.0,12.0,0.000000,38,0.0,0.0,-18.0,0.0,1.000000,75.280720,0.0,0.0,0.0,129041.512,91.0,37.0,26.0,18.0,481.0,625.0,653.0,22.0,28.0,186090.552,47.0,26.0,22.0,23.0,735.0,757.0,853.0,21.0,96.0,757.0,21.0,32454.007,12.0,8.0,3.0,4.0,125.0,129.0,152.0,10.0,23.0,22.0,21.0,10.0,62.0,12906.045,48.0,49.0,43.0,8410.586,35.0,34.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,4.0,3.0,0.0,0.0,11137.376,47.0,46.0,3.0,3.0,0.623301,35.0,18.0,753.0,157566.0320,21.5,691.0,62.0,-601.0,-125112.0250,-11.5,-562.0,-39.0,-701.0,-153636.545,-11.0,-628.0,-73.0,200.0,57049.040,132.0,68.0,-48293.7525,-248.0,-178.0,-6.0,-2.5,19.0,4495.459,13.0,15.0,15.666667,3712.458667,0.166667,485.947417,1.000000,-20.282392,1.0,12.900000,1.0,15.666667,8.857143,3.0,4.0,10.0,10.0,0.170068,12.900000,0.564516,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
11,dfLS2/Pom6O3iUpo+mf/K1Bc6g+7LFKzoNf+zlJtDoQ=,1,1.0,0.0,NaN,7.0,20140323.0,30.0,129.0,149.0,30.000000,124.07143,136.857150,51.321430,12.785714,30.0,99.0,99.0,62.0,0.0,1.0,3.0,29.0,1.0,713.0,55.0,0.103448,41,1.0,0.0,-7.0,0.0,0.664430,156.568710,0.0,0.0,0.0,60226.759,62.0,14.0,16.0,10.0,219.0,293.0,321.0,17.0,28.0,44063.061,43.0,13.0,15.0,9.0,166.0,239.0,246.0,12.0,7.0,239.0,12.0,32145.367,8.0,4.0,3.0,5.0,123.0,119.0,143.0,9.0,24.0,17.0,12.0,9.0,59.0,13134.818,51.0,39.0,53.0,12224.895,52.0,51.0,31.0,6785.654,20.0,29.0,0.0,0.000,0.0,0.0,3.0,4.0,2.0,0.0,0.000,0.0,0.0,0.0,0.0,0.909844,51.0,7.0,283.5,52144.9100,14.5,266.0,17.5,-140.5,-19999.5430,-5.5,-147.0,6.5,-103.0,-11917.694,-3.0,-120.0,17.0,-75.0,-16163.698,-54.0,-21.0,-14040.6960,-87.0,-48.0,-4.0,-2.0,6.0,909.923,-1.0,-12.0,0.000000,0.000000,-19.666667,-4378.272667,0.000000,-5.239631,1.0,13.222222,0.0,0.000000,8.428571,0.0,3.0,9.0,9.0,0.740964,13.222222,0.864407,1,1,0,1,0,0,0,1,1,0,1,0,0.0000,NaN
12,a7AtvhlY8KnKZGpiVe+4HhFerqTEgmno3x7Rc7YGwzw=,1,13.0,32.0,NaN,7.0,20140324.0,30.0,149.0,149.0,28.800000,149.00000,143.040000,30.480000,-5.960000,30.0,149.0,149.0,28.0,0.0,1.0,0.0,26.0,1.0,762.0,4.0,0.000000,41,1.0,0.0,-24.0,0.0,1.000000,0.000000,0.0,0.0,0.0,66802.001,107.0,17.0,17.0,23.0,234.0,268.0,398.0,22.0,130.0,49900.176,98.0,25.0,20.0,21.0,171.0,270.0,335.0,21.0,65.0,240.0,19.0,52033.364,91.0,25.0,18.0,23.0,181.0,217.0,338.0,20.0,121.0,22.0,21.0,20.0,78.0,12603.768,43.0,48.0,66.0,12517.630,48.0,51.0,146.0,20218.860,63.0,84.0,84.0,12922.157,50.0,64.0,5.0,5.0,7.0,5.0,0.000,0.0,0.0,0.0,0.0,0.957413,27.0,3.0,366.5,58351.0885,21.5,269.0,97.5,-28.5,-6317.7245,-1.5,-52.0,23.5,3.0,2133.188,-1.0,-53.0,56.0,-63.0,-16901.825,2.0,-65.0,-7384.3185,-25.5,-26.5,-1.0,-4.5,12.0,86.138,-5.0,-3.0,0.000000,0.000000,-15.600000,-2520.753600,0.000000,-2.477358,1.0,10.850000,0.0,0.000000,11.142857,0.0,5.0,20.0,20.0,1.058480,10.850000,0.346154,1,1,0,1,0,0,0,1,0,0,0,0,0.0000,NaN
13,F45GsXJIeLvzUJqz/v4R/6CVYPdek7K4Leu+aqbCRo8=,1,1.0,0.0,NaN,3.0,20140402.0,30.0,149.0,149.0,30.000000,149.00000,149.000000,30.937500,0.000000,30.0,149.0,149.0,30.0,0.0,0.0,0.0,17.0,1.0,764.0,25.0,0.000000,38,0.0,0.0,-5.0,0.0,1.000000,92.436460,0.0,0.0,0.0,147908.149,71.0,13.0,13.0,19.0,531.0,506.0,647.0,20.0,141.0,247184.989,137.0,31.0,14.0,47.0,890.0,679.0,1119.0,26.0,440.0,663.0,25.0,290666.077,105.0,29.0,21.0,37.0,1053.0,921.0,1245.0,25.0,324.0,20.0,26.0,25.0,259.0,57775.777,200.0,206.0,453.0,109023.522,405.0,340.0,441.0,101606.257,364.0,301.0,85.0,19007.774,67.0,62.0,7.0,7.0,7.0,3.0,7632.803,33.0,28.0,2.0,2.0,0.614616,66.0,3.0,883.0,197546.5690,23.0,592.5,290.5,362.0,93119.5080,2.0,328.5,33.5,126.0,43481.088,-1.0,242.0,-116.0,472.0,99276.840,173.0,299.0,71378.9640,207.5,261.0,2.5,91.5,-194.0,-51247.745,-205.0,-134.0,16.500000,3816.401500,-20.500000,-4437.280929,0.666667,11.145455,1.0,36.840000,1.0,11.000000,37.000000,2.0,7.0,25.0,25.0,1.183146,36.840000,0.254826,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
14,SJCoxreWp6Cu9WPitvAT6pZ9gChiSR4tWP4lvJGdxSM=,1,12.0,21.0,male,3.0,20140407.0,30.0,150.0,150.0,30.000000,149.94737,149.947370,30.000000,0.000000,30.0,180.0,180.0,30.0,0.0,0.0,0.0,20.0,2.0,753.0,20.0,0.000000,28,0.0,0.0,-10.0,0.0,1.200000,0.000000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,241.209,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,465214.749,74.0,26.0,22.0,24.0,1788.0,1800.0,1934.0,21.0,134.0,0.0,1.0,21.0,751.0,181591.140,697.0,693.0,524.0,124872.963,482.0,488.0,360.0,83900.047,325.0,336.0,0.0,0.000,0.0,0.0,7.0,7.0,4.0,0.0,74850.600,299.0,283.0,3.0,3.0,0.396007,141.0,10.0,0.5,120.6045,0.5,0.5,0.0,1933.5,465094.1445,20.5,1799.5,134.0,1933.0,464973.540,20.0,1799.0,134.0,1.0,241.209,1.0,0.0,232607.3745,900.0,894.0,10.5,67.0,227.0,56718.171,215.0,205.0,99.666667,24950.201667,-7.619048,-991.388905,1.000000,16.957143,1.0,85.714286,1.0,99.666667,107.285714,3.0,7.0,21.0,21.0,-2.000000,85.714286,0.187750,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
15,Oo2RDQixJ0pRWqec4/CksiKwhz0Za0yU2GIQtKa1JFk=,1,6.0,20.0,female,9.0,20140415.0,30.0,149.0,149.0,26.714285,127.71429,127.714290,26.714285,0.000000,30.0,149.0,149.0,30.0,0.0,0.0,0.0,8.0,1.0,725.0,28.0,0.000000,38,0.0,0.0,-2.0,0.0,1.000000,290.772520,0.0,0.0,0.0,93707.378,264.0,98.0,85.0,75.0,203.0,484.0,725.0,27.0,241.0,10598.769,12.0,11.0,4.0,5.0,31.0,56.0,63.0,4.0,7.0,24.0,3.0,23881.078,128.0,44.0,21.0,12.0,50.0,227.0,255.0,14.0,28.0,27.0,4.0,14.0,95.0,3495.710,1.0,87.0,49.0,6569.453,17.0,41.0,13.0,1790.587,4.0,11.0,88.0,13544.726,37.0,77.0,3.0,5.0,1.0,4.0,3751.308,46.0,43.0,2.0,2.0,1.008133,81.0,6.0,394.0,52153.0735,15.5,270.0,124.0,-139.0,-28271.9955,-1.5,-43.0,-96.0,192.0,13282.309,10.0,171.0,21.0,-662.0,-83108.609,-428.0,-234.0,-34913.1500,-128.5,-76.5,-6.5,-106.5,46.0,-3073.743,-16.0,46.0,23.000000,1875.654000,-8.666667,710.417333,0.666667,-1.028571,1.0,16.214286,1.0,15.333333,13.571429,2.0,3.0,14.0,14.0,1.612903,16.214286,0.852632,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,NaN
16,f91n3lDipDjRtAVNgMGnTsxP0VrzDsfB0Hdth12gqQE=,1,1.0,0.0,NaN,7.0,20140420.0,30.0,149.0,149.0,30.000000,143.64285,149.000000,249.500000,5.357143,30.0,149.0,149.0,0.0,1.0,1.0,1.0,29.0,1.0,608.0,163.0,0.034483,41,1.0,0.0,163.0,0.0,1.000000,180.492540,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,0,0.0000,NaN

In [5]:
full_df.shape

(970960, 160)

In [6]:
full_df.payment_toggle_state_flips.value_counts()

payment_toggle_state_flips
0.0    915165
1.0     27588
2.0     21624
3.0      4056
Name: count, dtype: int64

In [7]:
pd.set_option('display.max_rows',None)

In [8]:
check_df = full_df.loc[full_df['city'].isna()]

In [9]:
check_df.head(50)

,msno,is_churn,city,bd,gender,registered_via,registration_init_time,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mode_plan_list_price,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_ex_latest_mean_discount_amount,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,hist_ex_latest_mode_is_auto_renew,recent_autorenew_intent_trend,hist_expiration_recency_days,payment_toggle_state_flips,payment_elasticity_vector,replenishment_consistency_variance,payment_discount_amount,payment_discount_ratio,is_promo_tier_subscriber,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,jan_pre_w3_num_unq,jan_pre_w3_days_active,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,dec_raw_log_rows,jan_raw_log_rows,feb_raw_log_rows,total_songs_w0,total_secs_w0,num_100_w0,num_unq_w0,total_songs_w1,total_secs_w1,num_100_w1,num_unq_w1,total_songs_w2,total_secs_w2,num_100_w2,num_unq_w2,total_songs_w3,total_secs_w3,num_100_w3,num_unq_w3,active_days_w0,active_days_w1,active_days_w2,active_days_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,last_3d_raw_rows,coefficient_of_daily_variation_feb,max_single_day_songs_w0,inactivity_chunkiness_index_feb,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,trend_3m_monthly_velocity_total_secs,trend_3m_monthly_velocity_num_unq,trend_3m_monthly_velocity_num_100,trend_3m_monthly_velocity_days_active,trend_3m_monthly_velocity_repeat_songs,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,feb_daily_session_density,feb_daily_variety_density,last_3d_micro_session_density,raw_last_3d_daily_songs,raw_w0_daily_songs,raw_last_3d_active_days,raw_w0_active_days,raw_feb_log_rows,feb_true_active_days,true_relative_performance_ratio_complete,active_day_engagement_density_feb,extreme_stream_compression_ratio_w0,inter_auto_renew_x_fading_3d_stats,inter_auto_renew_x_last_3d_low_unq,inter_auto_renew_x_w0_structural_slump,inter_auto_renew_x_multi_window_decay,inter_auto_renew_x_engagement_desert,inter_auto_renew_x_promo_wall_cross,inter_auto_renew_x_ghost_billing_disconnect,inter_loyal_x_low_3d_unq,inter_loyal_x_low_tier_payer,inter_autorenew_x_desert_payer,inter_autorenew_x_low_tier_payer,is_legacy_ghost,ghost_group_base_rate,time_active
28,NTOh3fAZrLoIyE1lxoRpp2lzEraNnnWbUvOhrmO1bUM=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,142.437500,149.000000,218.562500,6.562500,30.0,149.0,149.0,0.0,1.0,1.0,1.0,33.0,1.0,655.0,116.0,0.030303,41,1.0,0.0,116.0,0.0,1.000000,28.296055,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
59,+wisdxP166qHezQOKLPv4l4AfZClRF3ExWGD2rzYYCU=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,28.571428,141.904750,141.904750,30.523810,0.000000,30.0,149.0,149.0,31.0,0.0,1.0,0.0,22.0,1.0,702.0,0.0,0.000000,41,1.0,0.0,-31.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
75,P9FjH43/pjIS6PwcXP8VcA+P4RTq/mH+F3DLuXDpFkE=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.578947,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,20.0,1.0,581.0,3.0,0.000000,41,1.0,0.0,-25.0,0.0,1.000000,183.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
85,Ybp7mbACy/qnytzEr8rZykiEyL23ESsAIZRo17VAT/8=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.555555,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,19.0,1.0,550.0,13.0,0.000000,41,1.0,0.0,-15.0,0.0,1.000000,0.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
129,r0ND2OhGFAUltb62mwbwM7W9nnI+MMA3IAdBHk3abbI=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.461538,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,14.0,1.0,396.0,7.0,0.000000,41,1.0,0.0,-21.0,0.0,1.000000,24.904260,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
145,YOF2Z5cnRQQzJ0+jO1k+0nkQ5rO2KDZA1x+XbZ2vPaw=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,21.0,0.000000,41,1.0,0.0,-7.0,0.0,1.000000,0.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
146,e0N3u3laGuzrocxSIezxFVU+uNuiiN4RAAhr36rmV0Y=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,21.0,0.000000,41,1.0,0.0,-7.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
154,47WmILK1vHIz0iCDMX1elQNorVhh1aupLKq1R5ddBto=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,9.0,0.000000,41,1.0,0.0,-19.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
185,8Yfas8KHQ5UHsRwQ3Iesv2UXZ9FStQxCZ+TKaJ7Q+SA=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,29.600000,0.000000,30.0,129.0,129.0,27.0,0.0,1.0,0.0,6.0,1.0,153.0,16.0,0.000000,30,1.0,0.0,-11.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
187,i3dM2clmvJ72BUOymuMNRAXRi+SOdn8ZvHtHkfItZXc=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.166666,0.000000,30.0,99.0,99.0,0.0,1.0,1.0,0.0,7.0,1.0,157.0,7.0,0.000000,41,1.0,0.0,7.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
196,5vIqhBLMxQr8q/ZSHwcOxR6rc9WJnSFK5t7i8UB0n90=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,30.000000,0.000000,0.000000,30.000000,0.000000,90.0,0.0,0.0,97.0,0.0,0.0,0.0,1.0,0.0,0.0,94.0,0.000000,-1,-1.0,0.0,-3.0,0.0,0.000000,-1.000000,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
201,R4BU1nriM4kJ8GlbwX+uijiX5WC6v3QxlHgQ3Yqyh6A=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,29.000000,0.000000,30.0,129.0,129.0,0.0,1.0,1.0,0.0,4.0,1.0,75.0,1.0,0.000000,30,1.0,0.0,1.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
202,ZpboqV+244iMAeyKObEcf057ZQlDI5ndU9aqq6dABKc=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,149.000000,149.000000,30.500000,0.000000,30.0,149.0,149.0,28.0,0.0,1.0,0.0,3.0,1.0,61.0,7.0,0.000000,41,1.0,0.0,-21.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,1,0.0542,NaN
218,nCInqDaNfoMEJ1XRqjo43gYZprZqjJhBgkFrHPlX8f4=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,30.000000,0.000000,0.000000,30.000000,0.000000,30.0,99.0,99.0,27.0,0.0,1.0,0.0,1.0,0.0,0.0,14.0,0.000000,-1,-1.0,0.0,-13.0,0.0,0.000000,-1.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
224,ls/2eT9UWbyV4tNdfZ4MFgUVY0c4Rx5WM1uLWVdjfVs=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
225,I8ovHkG/uALsd3JaclAD/aCCmxSBlkbo7YwTCJlpRGU=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
227,7P0KCwKkNgAmFFd55q4Zg0J83FNetM0DmTf/7cWb8DY=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
252,PozYMLxq3/hQdk3eKXF6nKGFRRdWRpHkSDgar3tAGOA=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,20.000000,149.000000,99.333336,57.666668,-49.666668,30.0,149.0,149.0,95.0,0.0,1.0,0.0,19.0,1.0,610.0,90.0,0.000000,34,1.0,0.0,-5.0,0.0,1.000000,91.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,1,0.0542,NaN
292,dXQ0JnRaRfuMhdzeehqlsN+GKuYodDI8WsSDnXGKBbA=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,31.480000,0.000000,30.0,129.0,129.0,29.0,0.0,1.0,0.0,26.0,1.0,762.0,9.0,0.000000,41,1.0,0.0,-20.0,0.0,1.000000,60.565952,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
293,I6gnX1A8/k2h30F2Mn6MeDa3UM8/8tjZ6MzffejIEpQ=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,28.750000,129.000000,123.625000,32.458332,-5.375000,30.0,129.0,129.0,30.0,0.0,1.0,0.0,25.0,1.0,731.0,28.0,0.000000,41,1.0,0.0,-2.0,0.0,1.000000,65.083710,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
345,WjWeljWIngo2lWf1sXQHBG3wVbHnllZwoxBGuzWq6Rg=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,109.000000,109.000000,28.200000,0.000000,30.0,99.0,99.0,0.0,1.0,1.0,1.0,16.0,1.0,783.0,5.0,0.062500,41,1.0,0.0,5.0,0.0,1.000000,275.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
403,pJHMGVS7WHq35l55pKZ6Ilx+NXcj6fN9jUQCswD+anc=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,28.960000,149.000000,143.040000,29.600000,-5.960000,30.0,149.0,149.0,27.0,0.0,1.0,0.0,26.0,1.0,763.0,20.0,0.000000,37,1.0,0.0,-7.0,0.0,1.000000,38.663790,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN

In [10]:
check_df.shape

(109993, 160)

In [11]:
check_df.is_churn.sum()

np.int64(5882)

In [12]:
check_df.hist_latest_is_auto_renew.sum()

np.float64(109255.0)

In [13]:
full_df.time_active.max()

np.float64(nan)

In [14]:
check = check_df[check_df['is_churn'] == 1]

In [15]:
check.head(100)

,msno,is_churn,city,bd,gender,registered_via,registration_init_time,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mode_plan_list_price,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_ex_latest_mean_discount_amount,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,hist_ex_latest_mode_is_auto_renew,recent_autorenew_intent_trend,hist_expiration_recency_days,payment_toggle_state_flips,payment_elasticity_vector,replenishment_consistency_variance,payment_discount_amount,payment_discount_ratio,is_promo_tier_subscriber,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,jan_pre_w3_num_unq,jan_pre_w3_days_active,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,dec_raw_log_rows,jan_raw_log_rows,feb_raw_log_rows,total_songs_w0,total_secs_w0,num_100_w0,num_unq_w0,total_songs_w1,total_secs_w1,num_100_w1,num_unq_w1,total_songs_w2,total_secs_w2,num_100_w2,num_unq_w2,total_songs_w3,total_secs_w3,num_100_w3,num_unq_w3,active_days_w0,active_days_w1,active_days_w2,active_days_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,last_3d_raw_rows,coefficient_of_daily_variation_feb,max_single_day_songs_w0,inactivity_chunkiness_index_feb,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,trend_3m_monthly_velocity_total_secs,trend_3m_monthly_velocity_num_unq,trend_3m_monthly_velocity_num_100,trend_3m_monthly_velocity_days_active,trend_3m_monthly_velocity_repeat_songs,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,feb_daily_session_density,feb_daily_variety_density,last_3d_micro_session_density,raw_last_3d_daily_songs,raw_w0_daily_songs,raw_last_3d_active_days,raw_w0_active_days,raw_feb_log_rows,feb_true_active_days,true_relative_performance_ratio_complete,active_day_engagement_density_feb,extreme_stream_compression_ratio_w0,inter_auto_renew_x_fading_3d_stats,inter_auto_renew_x_last_3d_low_unq,inter_auto_renew_x_w0_structural_slump,inter_auto_renew_x_multi_window_decay,inter_auto_renew_x_engagement_desert,inter_auto_renew_x_promo_wall_cross,inter_auto_renew_x_ghost_billing_disconnect,inter_loyal_x_low_3d_unq,inter_loyal_x_low_tier_payer,inter_autorenew_x_desert_payer,inter_autorenew_x_low_tier_payer,is_legacy_ghost,ghost_group_base_rate,time_active
28,NTOh3fAZrLoIyE1lxoRpp2lzEraNnnWbUvOhrmO1bUM=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,142.437500,149.000000,218.562500,6.562500,30.0,149.0,149.0,0.0,1.0,1.0,1.0,33.0,1.0,655.0,116.0,0.030303,41,1.0,0.0,116.0,0.0,1.000000,28.296055,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
59,+wisdxP166qHezQOKLPv4l4AfZClRF3ExWGD2rzYYCU=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,28.571428,141.904750,141.904750,30.523810,0.000000,30.0,149.0,149.0,31.0,0.0,1.0,0.0,22.0,1.0,702.0,0.0,0.000000,41,1.0,0.0,-31.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
75,P9FjH43/pjIS6PwcXP8VcA+P4RTq/mH+F3DLuXDpFkE=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.578947,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,20.0,1.0,581.0,3.0,0.000000,41,1.0,0.0,-25.0,0.0,1.000000,183.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
85,Ybp7mbACy/qnytzEr8rZykiEyL23ESsAIZRo17VAT/8=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.555555,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,19.0,1.0,550.0,13.0,0.000000,41,1.0,0.0,-15.0,0.0,1.000000,0.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
129,r0ND2OhGFAUltb62mwbwM7W9nnI+MMA3IAdBHk3abbI=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.461538,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,14.0,1.0,396.0,7.0,0.000000,41,1.0,0.0,-21.0,0.0,1.000000,24.904260,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
145,YOF2Z5cnRQQzJ0+jO1k+0nkQ5rO2KDZA1x+XbZ2vPaw=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,21.0,0.000000,41,1.0,0.0,-7.0,0.0,1.000000,0.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
146,e0N3u3laGuzrocxSIezxFVU+uNuiiN4RAAhr36rmV0Y=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,21.0,0.000000,41,1.0,0.0,-7.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
154,47WmILK1vHIz0iCDMX1elQNorVhh1aupLKq1R5ddBto=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.545454,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,336.0,9.0,0.000000,41,1.0,0.0,-19.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
185,8Yfas8KHQ5UHsRwQ3Iesv2UXZ9FStQxCZ+TKaJ7Q+SA=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,29.600000,0.000000,30.0,129.0,129.0,27.0,0.0,1.0,0.0,6.0,1.0,153.0,16.0,0.000000,30,1.0,0.0,-11.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
187,i3dM2clmvJ72BUOymuMNRAXRi+SOdn8ZvHtHkfItZXc=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.000000,99.000000,30.166666,0.000000,30.0,99.0,99.0,0.0,1.0,1.0,0.0,7.0,1.0,157.0,7.0,0.000000,41,1.0,0.0,7.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
196,5vIqhBLMxQr8q/ZSHwcOxR6rc9WJnSFK5t7i8UB0n90=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,30.000000,0.000000,0.000000,30.000000,0.000000,90.0,0.0,0.0,97.0,0.0,0.0,0.0,1.0,0.0,0.0,94.0,0.000000,-1,-1.0,0.0,-3.0,0.0,0.000000,-1.000000,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
201,R4BU1nriM4kJ8GlbwX+uijiX5WC6v3QxlHgQ3Yqyh6A=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,29.000000,0.000000,30.0,129.0,129.0,0.0,1.0,1.0,0.0,4.0,1.0,75.0,1.0,0.000000,30,1.0,0.0,1.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
202,ZpboqV+244iMAeyKObEcf057ZQlDI5ndU9aqq6dABKc=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,149.000000,149.000000,30.500000,0.000000,30.0,149.0,149.0,28.0,0.0,1.0,0.0,3.0,1.0,61.0,7.0,0.000000,41,1.0,0.0,-21.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,1,0.0542,NaN
218,nCInqDaNfoMEJ1XRqjo43gYZprZqjJhBgkFrHPlX8f4=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,30.000000,0.000000,0.000000,30.000000,0.000000,30.0,99.0,99.0,27.0,0.0,1.0,0.0,1.0,0.0,0.0,14.0,0.000000,-1,-1.0,0.0,-13.0,0.0,0.000000,-1.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
224,ls/2eT9UWbyV4tNdfZ4MFgUVY0c4Rx5WM1uLWVdjfVs=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
225,I8ovHkG/uALsd3JaclAD/aCCmxSBlkbo7YwTCJlpRGU=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
227,7P0KCwKkNgAmFFd55q4Zg0J83FNetM0DmTf/7cWb8DY=,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0.0542,NaN
252,PozYMLxq3/hQdk3eKXF6nKGFRRdWRpHkSDgar3tAGOA=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,20.000000,149.000000,99.333336,57.666668,-49.666668,30.0,149.0,149.0,95.0,0.0,1.0,0.0,19.0,1.0,610.0,90.0,0.000000,34,1.0,0.0,-5.0,0.0,1.000000,91.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,1,0.0542,NaN
292,dXQ0JnRaRfuMhdzeehqlsN+GKuYodDI8WsSDnXGKBbA=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,30.000000,129.000000,129.000000,31.480000,0.000000,30.0,129.0,129.0,29.0,0.0,1.0,0.0,26.0,1.0,762.0,9.0,0.000000,41,1.0,0.0,-20.0,0.0,1.000000,60.565952,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
293,I6gnX1A8/k2h30F2Mn6MeDa3UM8/8tjZ6MzffejIEpQ=,1,NaN,NaN,NaN,NaN,NaN,30.0,129.0,129.0,28.750000,129.000000,123.625000,32.458332,-5.375000,30.0,129.0,129.0,30.0,0.0,1.0,0.0,25.0,1.0,731.0,28.0,0.000000,41,1.0,0.0,-2.0,0.0,1.000000,65.083710,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
345,WjWeljWIngo2lWf1sXQHBG3wVbHnllZwoxBGuzWq6Rg=,1,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,109.000000,109.000000,28.200000,0.000000,30.0,99.0,99.0,0.0,1.0,1.0,1.0,16.0,1.0,783.0,5.0,0.062500,41,1.0,0.0,5.0,0.0,1.000000,275.500000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,1,1,1,1,0.0542,NaN
403,pJHMGVS7WHq35l55pKZ6Ilx+NXcj6fN9jUQCswD+anc=,1,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,28.960000,149.000000,143.040000,29.600000,-5.960000,30.0,149.0,149.0,27.0,0.0,1.0,0.0,26.0,1.0,763.0,20.0,0.000000,37,1.0,0.0,-7.0,0.0,1.000000,38.663790,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN

In [16]:
check.time_active.value_counts()

Series([], Name: count, dtype: int64)

In [17]:
check_df.hist_snap_feb_days_active.value_counts().head()

hist_snap_feb_days_active
27.0    2
0.0     2
23.0    2
28.0    2
13.0    2
Name: count, dtype: int64

In [18]:
other_check = check_df[check_df.is_churn == 0]

In [19]:
other_check.head(10)

,msno,is_churn,city,bd,gender,registered_via,registration_init_time,hist_ex_latest_mode_payment_plan_days,hist_ex_latest_mode_actual_amount_paid,hist_ex_latest_mode_plan_list_price,hist_ex_latest_mean_payment_plan_days,hist_ex_latest_mean_actual_amount_paid,hist_ex_latest_mean_plan_list_price,hist_ex_latest_mean_coverage_days,hist_ex_latest_mean_discount_amount,hist_latest_payment_plan_days,hist_latest_plan_list_price,hist_latest_actual_amount_paid,hist_latest_coverage_days,hist_latest_is_cancel,hist_latest_is_auto_renew,hist_total_cancels,hist_transaction_count,hist_payment_method_change,hist_tenure_days,hist_recency_days,hist_cancel_rate,payment_method_mode,hist_ex_latest_mode_is_auto_renew,recent_autorenew_intent_trend,hist_expiration_recency_days,payment_toggle_state_flips,payment_elasticity_vector,replenishment_consistency_variance,payment_discount_amount,payment_discount_ratio,is_promo_tier_subscriber,hist_snap_dec_total_secs,hist_snap_dec_num_25,hist_snap_dec_num_50,hist_snap_dec_num_75,hist_snap_dec_num_985,hist_snap_dec_num_100,hist_snap_dec_num_unq,hist_snap_dec_total_songs,hist_snap_dec_days_active,hist_snap_dec_repeat_songs,hist_snap_jan_total_secs,hist_snap_jan_num_25,hist_snap_jan_num_50,hist_snap_jan_num_75,hist_snap_jan_num_985,hist_snap_jan_num_100,hist_snap_jan_num_unq,hist_snap_jan_total_songs,hist_snap_jan_days_active,hist_snap_jan_repeat_songs,jan_pre_w3_num_unq,jan_pre_w3_days_active,hist_snap_feb_total_secs,hist_snap_feb_num_25,hist_snap_feb_num_50,hist_snap_feb_num_75,hist_snap_feb_num_985,hist_snap_feb_num_100,hist_snap_feb_num_unq,hist_snap_feb_total_songs,hist_snap_feb_days_active,hist_snap_feb_repeat_songs,dec_raw_log_rows,jan_raw_log_rows,feb_raw_log_rows,total_songs_w0,total_secs_w0,num_100_w0,num_unq_w0,total_songs_w1,total_secs_w1,num_100_w1,num_unq_w1,total_songs_w2,total_secs_w2,num_100_w2,num_unq_w2,total_songs_w3,total_secs_w3,num_100_w3,num_unq_w3,active_days_w0,active_days_w1,active_days_w2,active_days_w3,last_3d_secs,last_3d_songs,last_3d_unq,last_3d_active_days,last_3d_raw_rows,coefficient_of_daily_variation_feb,max_single_day_songs_w0,inactivity_chunkiness_index_feb,hist_prior_2m_avg_songs,hist_prior_2m_avg_secs,hist_prior_2m_avg_days_active,hist_prior_2m_avg_unq,hist_prior_2m_avg_repeats,feb_songs_vs_prior_avg_delta,feb_secs_vs_prior_avg_delta,feb_active_days_vs_prior_avg_delta,feb_unq_vs_prior_avg_delta,feb_repeats_vs_prior_avg_delta,feb_vs_jan_songs_delta,feb_vs_jan_secs_delta,feb_vs_jan_active_days_delta,feb_vs_jan_unq_delta,feb_vs_jan_repeats_delta,jan_vs_dec_songs_delta,jan_vs_dec_secs_delta,jan_vs_dec_unq_delta,jan_vs_dec_repeats_delta,trend_3m_monthly_velocity_total_secs,trend_3m_monthly_velocity_num_unq,trend_3m_monthly_velocity_num_100,trend_3m_monthly_velocity_days_active,trend_3m_monthly_velocity_repeat_songs,songs_final_week_vs_prior_week_delta,secs_final_week_vs_prior_week_delta,completed_songs_final_week_vs_prior_week_delta,unique_songs_final_week_vs_prior_week_delta,avg_daily_songs_last_3d,avg_daily_secs_last_3d,songs_last_3d_vs_w0_daily_delta,secs_last_3d_vs_w0_daily_delta,last_3d_active_rate,last2wk_vs_last_month_numunq_avg_diff,feb_daily_session_density,feb_daily_variety_density,last_3d_micro_session_density,raw_last_3d_daily_songs,raw_w0_daily_songs,raw_last_3d_active_days,raw_w0_active_days,raw_feb_log_rows,feb_true_active_days,true_relative_performance_ratio_complete,active_day_engagement_density_feb,extreme_stream_compression_ratio_w0,inter_auto_renew_x_fading_3d_stats,inter_auto_renew_x_last_3d_low_unq,inter_auto_renew_x_w0_structural_slump,inter_auto_renew_x_multi_window_decay,inter_auto_renew_x_engagement_desert,inter_auto_renew_x_promo_wall_cross,inter_auto_renew_x_ghost_billing_disconnect,inter_loyal_x_low_3d_unq,inter_loyal_x_low_tier_payer,inter_autorenew_x_desert_payer,inter_autorenew_x_low_tier_payer,is_legacy_ghost,ghost_group_base_rate,time_active
52347,yWkBkojk9430HspZFVyowwRVH0D6ruFOWd6qMHz8Yhw=,0,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.00000,99.00000,30.333334,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,4.0,1.0,91.0,10.0,0.0,41,1.0,0.0,-18.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
52395,lQE44VEn1TVcopNgIAOcnS5Ke73fKbKzUnLVCtuPDhI=,0,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,138.35715,149.00000,30.571428,10.642858,30.0,149.0,149.0,28.0,0.0,1.0,0.0,15.0,1.0,428.0,11.0,0.0,41,1.0,0.0,-17.0,0.0,1.000000,15.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,0,1,0.0542,NaN
52397,s453MqSKJdvJilVFWSvR+bvcNjKr2GN3gg3F2xuPRik=,0,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.00000,99.00000,30.538462,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,14.0,1.0,397.0,1.0,0.0,41,1.0,0.0,-27.0,0.0,1.000000,24.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
52453,xql4zjgb0PDKYxaZGjuhvOX5xJ9bXzIZCYkryCvNSOo=,0,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.00000,99.00000,30.636364,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,12.0,1.0,337.0,18.0,0.0,41,1.0,0.0,-10.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
52503,JB4qd3Kyb/kZikjbhqeOdAjg/ZMIXFC13R2H2F4uwHI=,0,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.00000,99.00000,30.500000,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,9.0,1.0,244.0,5.0,0.0,41,1.0,0.0,-23.0,0.0,1.000000,15.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
52521,EeB646stPjwQ0YR83EzWzEz/H18rfNoZwpFhc2ystTs=,0,NaN,NaN,NaN,NaN,NaN,30.0,99.0,99.0,30.000000,99.00000,99.00000,30.625000,0.000000,30.0,99.0,99.0,28.0,0.0,1.0,0.0,9.0,1.0,245.0,5.0,0.0,41,1.0,0.0,-23.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,1,1,1,0.0542,NaN
52542,pZlSU+hb0CRt2imHz1VX+kU1iswDFE0Hhkn5Rd244cQ=,0,NaN,NaN,NaN,NaN,NaN,30.0,149.0,129.0,28.800000,139.40000,133.44000,31.440000,-5.960000,30.0,149.0,149.0,29.0,0.0,1.0,0.0,26.0,1.0,760.0,27.0,0.0,41,1.0,0.0,-2.0,0.0,1.155039,65.596410,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
52559,cLL11OdVXAEz1d7m2NEN6zoF3MkCV5TkQTr+Nvsz8+o=,0,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,30.000000,149.00000,149.00000,31.480000,0.000000,30.0,149.0,149.0,29.0,0.0,1.0,0.0,26.0,1.0,762.0,11.0,0.0,41,1.0,0.0,-18.0,0.0,1.000000,25.703842,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
52562,0GSUvWMgJ2dKPdZDt94FLh9Z4o/eDZqbZSLh4Ev5L3U=,0,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,28.800000,149.00000,143.04000,31.480000,-5.960000,30.0,149.0,149.0,29.0,0.0,1.0,0.0,26.0,1.0,762.0,4.0,0.0,41,1.0,0.0,-25.0,0.0,1.000000,220.899290,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN
52624,qEOnDQMpBMtAbmQtG17C3Slib9IkFDe31UyGeinxpc4=,0,NaN,NaN,NaN,NaN,NaN,30.0,149.0,149.0,21.428572,149.00000,106.42857,30.428572,-42.571430,30.0,149.0,149.0,31.0,0.0,1.0,0.0,22.0,1.0,700.0,0.0,0.0,33,1.0,0.0,-31.0,0.0,1.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,1,0,1,0,1,0.0542,NaN

In [20]:
print(full_df.hist_tenure_days.quantile(0.))

0.0

In [21]:
check_df.hist_transaction_count.value_counts()

hist_transaction_count
26.0    9242
14.0    7280
17.0    7216
16.0    6185
19.0    5984
18.0    5721
8.0     5474
13.0    5353
9.0     5302
20.0    5052
15.0    4911
3.0     4539
12.0    4510
22.0    4484
7.0     4481
1.0     4379
4.0     4039
5.0     3040
2.0     2861
10.0    2845
6.0     2354
11.0    1648
21.0     597
27.0     535
0.0      495
24.0     477
28.0     440
25.0     261
23.0     189
29.0      33
30.0      19
39.0      13
38.0       7
35.0       6
36.0       6
34.0       5
37.0       3
33.0       2
32.0       2
31.0       2
40.0       1
Name: count, dtype: int64

In [22]:
#drop =  [is_churn,msno]
#fix = [time_active,]
#cat= [registered_via,gender,city]
#impute the ghost accounts with a sentinel 
#impute gender with 'not_specified'

In [24]:
df = full_df

In [25]:
df.isna().sum()

msno                                                   0
is_churn                                               0
city                                              109993
bd                                                109993
gender                                            582055
registered_via                                    109993
registration_init_time                            109993
hist_ex_latest_mode_payment_plan_days              41801
hist_ex_latest_mode_actual_amount_paid                 0
hist_ex_latest_mode_plan_list_price                41801
hist_ex_latest_mean_payment_plan_days               2527
hist_ex_latest_mean_actual_amount_paid              2527
hist_ex_latest_mean_plan_list_price                 2527
hist_ex_latest_mean_coverage_days                   2527
hist_ex_latest_mean_discount_amount                 2527
hist_latest_payment_plan_days                       2527
hist_latest_plan_list_price                            0
hist_latest_actual_amount_paid                         0
hist_latest_coverage_days                           2527
hist_latest_is_cancel                               2527
hist_latest_is_auto_renew                              0
hist_total_cancels                                  2527
hist_transaction_count                                 0
hist_payment_method_change                          2527
hist_tenure_days                                       0
hist_recency_days                                   2527
hist_cancel_rate                                    2527
payment_method_mode                                    0
hist_ex_latest_mode_is_auto_renew                   2527
recent_autorenew_intent_trend                       2527
hist_expiration_recency_days                        2527
payment_toggle_state_flips                          2527
payment_elasticity_vector                           2527
replenishment_consistency_variance                  2527
payment_discount_amount                             2527
payment_discount_ratio                              2527
is_promo_tier_subscriber                            2527
hist_snap_dec_total_secs                          177231
hist_snap_dec_num_25                              177231
hist_snap_dec_num_50                              177231
hist_snap_dec_num_75                              177231
hist_snap_dec_num_985                             177231
hist_snap_dec_num_100                             177231
hist_snap_dec_num_unq                             177231
hist_snap_dec_total_songs                         177231
hist_snap_dec_days_active                         177231
hist_snap_dec_repeat_songs                        177231
hist_snap_jan_total_secs                          177231
hist_snap_jan_num_25                              177231
hist_snap_jan_num_50                              177231
hist_snap_jan_num_75                              177231
hist_snap_jan_num_985                             177231
hist_snap_jan_num_100                             177231
hist_snap_jan_num_unq                             177231
hist_snap_jan_total_songs                         177231
hist_snap_jan_days_active                         177231
hist_snap_jan_repeat_songs                        177231
jan_pre_w3_num_unq                                177231
jan_pre_w3_days_active                            177231
hist_snap_feb_total_secs                          177231
hist_snap_feb_num_25                              177231
hist_snap_feb_num_50                              177231
hist_snap_feb_num_75                              177231
hist_snap_feb_num_985                             177231
hist_snap_feb_num_100                             177231
hist_snap_feb_num_unq                             177231
hist_snap_feb_total_songs                              0
hist_snap_feb_days_active                         177231
hist_snap_feb_repeat_songs                        177231
dec_raw_log_rows                                  177231
jan_raw_log_rows                                  177231
feb_raw_log_rows                                  177231
total_songs_w0                                         0
total_secs_w0                                          0
num_100_w0                                        177231
num_unq_w0                                             0
total_songs_w1                                    177231
total_secs_w1                                     177231
num_100_w1                                        177231
num_unq_w1                                        177231
total_songs_w2                                    177231
total_secs_w2                                     177231
num_100_w2                                        177231
num_unq_w2                                        177231
total_songs_w3                                    177231
total_secs_w3                                     177231
num_100_w3                                        177231
num_unq_w3                                        177231
active_days_w0                                    177231
active_days_w1                                    177231
active_days_w2                                    177231
active_days_w3                                    177231
last_3d_secs                                           0
last_3d_songs                                          0
last_3d_unq                                            0
last_3d_active_days                                    0
last_3d_raw_rows                                  177231
coefficient_of_daily_variation_feb                177231
max_single_day_songs_w0                           177231
inactivity_chunkiness_index_feb                        0
hist_prior_2m_avg_songs                           177231
hist_prior_2m_avg_secs                            177231
hist_prior_2m_avg_days_active                     177231
hist_prior_2m_avg_unq                             177231
hist_prior_2m_avg_repeats                         177231
feb_songs_vs_prior_avg_delta                      177231
feb_secs_vs_prior_avg_delta                       177231
feb_active_days_vs_prior_avg_delta                177231
feb_unq_vs_prior_avg_delta                        177231
feb_repeats_vs_prior_avg_delta                    177231
feb_vs_jan_songs_delta                            177231
feb_vs_jan_secs_delta                             177231
feb_vs_jan_active_days_delta                      177231
feb_vs_jan_unq_delta                              177231
feb_vs_jan_repeats_delta                          177231
jan_vs_dec_songs_delta                            177231
jan_vs_dec_secs_delta                             177231
jan_vs_dec_unq_delta                              177231
jan_vs_dec_repeats_delta                          177231
trend_3m_monthly_velocity_total_secs              177231
trend_3m_monthly_velocity_num_unq                 177231
trend_3m_monthly_velocity_num_100                 177231
trend_3m_monthly_velocity_days_active             177231
trend_3m_monthly_velocity_repeat_songs            177231
songs_final_week_vs_prior_week_delta              177231
secs_final_week_vs_prior_week_delta               177231
completed_songs_final_week_vs_prior_week_delta    177231
unique_songs_final_week_vs_prior_week_delta       177231
avg_daily_songs_last_3d                           177231
avg_daily_secs_last_3d                            177231
songs_last_3d_vs_w0_daily_delta                   177231
secs_last_3d_vs_w0_daily_delta                    177231
last_3d_active_rate                               177231
last2wk_vs_last_month_numunq_avg_diff             177231
feb_daily_session_density                         177231
feb_daily_variety_density                         177231
last_3d_micro_session_density                     177231
raw_last_3d_daily_songs                           177231
raw_w0_daily_songs                                177231
raw_last_3d_active_days                           177231
raw_w0_active_days                                177231
raw_feb_log_rows                                  177231
feb_true_active_days                              177231
true_relative_performance_ratio_complete          177231
active_day_engagement_density_feb                 177231
extreme_stream_compression_ratio_w0               177231
inter_auto_renew_x_fading_3d_stats                     0
inter_auto_renew_x_last_3d_low_unq                     0
inter_auto_renew_x_w0_structural_slump                 0
inter_auto_renew_x_multi_window_decay                  0
inter_auto_renew_x_engagement_desert                   0
inter_auto_renew_x_promo_wall_cross                    0
inter_auto_renew_x_ghost_billing_disconnect            0
inter_loyal_x_low_3d_unq                               0
inter_loyal_x_low_tier_payer                           0
inter_autorenew_x_desert_payer                         0
inter_autorenew_x_low_tier_payer                       0
is_legacy_ghost                                        0
ghost_group_base_rate                                  0
time_active                                       970960
dtype: int64

In [26]:
clean_date_strings = pd.to_numeric(df['registration_init_time'], errors='coerce') \
                           .astype('Int64') \
                           .astype(str) \
                           .str.replace('<NA>', '')  # Strip pandas' missing integer string representation
    
# Parse the standardized YYYYMMD string values into a standard datetime object
reg_dates = pd.to_datetime(clean_date_strings, format='%Y%m%d', errors='coerce')
snapshot_date = pd.Timestamp('2017-02-28')  
# Compute the exact time active span in days (missing accounts remain as NaN for now)
df['time_active'] = (snapshot_date - reg_dates).dt.days.astype('float32')
member_numerical_categoricals = ['city', 'bd', 'registered_via', 'registration_init_time', 'time_active']

print("Imputing -1 for numerical and categorical profile attributes...")
for col in member_numerical_categoricals:
    if col in df.columns:
        df[col] = df[col].fillna(-1)
        
        # Downcast primitives where appropriate to save memory footprint
        if col in ['city', 'registered_via']:
            df[col] = df[col].astype('int8')
        elif col in ['bd']:
            df[col] = df[col].astype('int16')
        elif col in ['registration_init_time', 'time_active']:
            df[col] = df[col].astype('float32') # Keeping float32 allows downstreams to know it's a numeric continuum

print("Imputing 'not_spec' for demographic gender gaps...")
if 'gender' in df.columns:
    df['gender'] = df['gender'].fillna('not_spec').astype(str)

Imputing -1 for numerical and categorical profile attributes...
Imputing 'not_spec' for demographic gender gaps...

In [27]:
print("--- STEP 1: RESOLVING THE SINGLE-TRANSACTION MODE GAPS ---")

# For users with exactly 1 transaction, copy their latest data to establish their historical baseline
mode_fallbacks = {
    'hist_ex_latest_mode_payment_plan_days': 'hist_latest_payment_plan_days',
    'hist_ex_latest_mode_plan_list_price': 'hist_latest_plan_list_price',
    'hist_ex_latest_mode_actual_amount_paid': 'hist_latest_actual_amount_paid',
    'hist_ex_latest_mode_is_auto_renew': 'hist_latest_is_auto_renew'
}

for mode_col, latest_col in mode_fallbacks.items():
    if mode_col in df.columns and latest_col in df.columns:
        initial_nan = df[mode_col].isna().sum()
        df[mode_col] = df[mode_col].fillna(df[latest_col])
        post_nan = df[mode_col].isna().sum()
        print(f"-> Mode {mode_col:<40} | Resolved {initial_nan - post_nan:,} single-tx records. Remaining NaNs: {post_nan:,}")


print("\n--- STEP 2: CONFLICT-FREE IMPUTATIONS FOR ZERO-TRANSACTION POOL (2,527 Users) ---")

# 1. Dedicated Sentinel Fills (Prevents overlapping with valid 0 or stable flags)
explicit_sentinel_fills = {
    'recent_autorenew_intent_trend': -9,       # -9 = Missing history (0 = Stable sequence)
    'latest_auto_renew_dropped': -9,           # -9 = Missing history (0 = No drop occurred)
    'hist_latest_is_auto_renew': -1,           # -1 = No billing records (0 = Manual renewer)
    'hist_ex_latest_mode_is_auto_renew': -1,   # -1 = No billing records (0 = Manual mode)
    'hist_latest_is_cancel': -1,               # -1 = No billing records (0 = Active/No cancel)
    'payment_method_mode': '-1',               # '-1' = Unknown payment channel string
    'hist_recency_days': -999,                 # Out-of-bounds timeline flags
    'hist_expiration_recency_days': -999,      # Out-of-bounds timeline flags
    'replenishment_consistency_variance': -1.0 # Standard native missing token
}

# 2. Pure Numeric Zero Fills (Where 0 is the literal absolute truth of having no transactions)
absolute_zero_fills = [
    'hist_transaction_count', 'hist_total_cancels', 'hist_payment_method_change', 
    'hist_tenure_days', 'hist_cancel_rate', 'payment_toggle_state_flips', 
    'payment_elasticity_vector', 'payment_discount_amount', 'payment_discount_ratio', 
    'is_promo_tier_subscriber', 'hist_ex_latest_mean_payment_plan_days', 
    'hist_ex_latest_mean_actual_amount_paid', 'hist_ex_latest_mean_plan_list_price', 
    'hist_ex_latest_mean_coverage_days', 'hist_ex_latest_mean_discount_amount',
    'hist_latest_payment_plan_days', 'hist_latest_plan_list_price', 
    'hist_latest_actual_amount_paid', 'hist_latest_coverage_days'
]

# Apply Explicit Sentinels
for col, fill_val in explicit_sentinel_fills.items():
    if col in df.columns:
        df[col] = df[col].fillna(fill_val)

# Apply Absolute Zeros
for col in absolute_zero_fills:
    if col in df.columns:
        df[col] = df[col].fillna(0.0)

print("Imputations complete. Verifying transaction feature matrix null states...")

# Final validation loop
tx_check_list = list(mode_fallbacks.keys()) + list(explicit_sentinel_fills.keys()) + absolute_zero_fills
all_clear = True
for col in tx_check_list:
    if col in df.columns:
        null_count = df[col].isna().sum()
        if null_count > 0:
            print(f"⚠️ Warning: {col} still has {null_count} NaNs!")
            all_clear = False

if all_clear:
    print("🎉 Success! Every transaction feature has been fully resolved without a single flag conflict.")
mode_zero_fills = [
    'hist_ex_latest_mode_payment_plan_days',
    'hist_ex_latest_mode_plan_list_price',
    'hist_ex_latest_mode_actual_amount_paid'
]

print("Patching remaining zero-transaction historical mode gaps...")
for col in mode_zero_fills:
    if col in df.columns:
        df[col] = df[col].fillna(0.0)
        print(f"-> {col} remaining NaNs: {df[col].isna().sum()}")

print("\n🎉 Verification check complete. Every column is now 100% clean!")

--- STEP 1: RESOLVING THE SINGLE-TRANSACTION MODE GAPS ---
-> Mode hist_ex_latest_mode_payment_plan_days    | Resolved 39,274 single-tx records. Remaining NaNs: 2,527
-> Mode hist_ex_latest_mode_plan_list_price      | Resolved 41,801 single-tx records. Remaining NaNs: 0
-> Mode hist_ex_latest_mode_actual_amount_paid   | Resolved 0 single-tx records. Remaining NaNs: 0
-> Mode hist_ex_latest_mode_is_auto_renew        | Resolved 2,527 single-tx records. Remaining NaNs: 0

--- STEP 2: CONFLICT-FREE IMPUTATIONS FOR ZERO-TRANSACTION POOL (2,527 Users) ---
Imputations complete. Verifying transaction feature matrix null states...
⚠️ Warning: hist_ex_latest_mode_payment_plan_days still has 2527 NaNs!
Patching remaining zero-transaction historical mode gaps...
-> hist_ex_latest_mode_payment_plan_days remaining NaNs: 0
-> hist_ex_latest_mode_plan_list_price remaining NaNs: 0
-> hist_ex_latest_mode_actual_amount_paid remaining NaNs: 0

🎉 Verification check complete. Every column is now 100% clean!

In [28]:
print("--- STEP 1: IDENTIFYING ALL REMAINING USER LOG COLUMNS ---")

# Isolate the exact 177,231 streaming log desert features from your feature matrix
user_log_cols = [
    'hist_snap_dec_total_secs', 'hist_snap_dec_num_25', 'hist_snap_dec_num_50', 
    'hist_snap_dec_num_75', 'hist_snap_dec_num_985', 'hist_snap_dec_num_100', 
    'hist_snap_dec_num_unq', 'hist_snap_dec_total_songs', 'hist_snap_dec_days_active', 
    'hist_snap_dec_repeat_songs', 'hist_snap_jan_total_secs', 'hist_snap_jan_num_25', 
    'hist_snap_jan_num_50', 'hist_snap_jan_num_75', 'hist_snap_jan_num_985', 
    'hist_snap_jan_num_100', 'hist_snap_jan_num_unq', 'hist_snap_jan_total_songs', 
    'hist_snap_jan_days_active', 'hist_snap_jan_repeat_songs', 'jan_pre_w3_num_unq', 
    'jan_pre_w3_days_active', 'hist_snap_feb_total_secs', 'hist_snap_feb_num_25', 
    'hist_snap_feb_num_50', 'hist_snap_feb_num_75', 'hist_snap_feb_num_985', 
    'hist_snap_feb_num_100', 'hist_snap_feb_num_unq', 'hist_snap_feb_days_active', 
    'hist_snap_feb_repeat_songs', 'dec_raw_log_rows', 'jan_raw_log_rows', 
    'feb_raw_log_rows', 'num_100_w0', 'total_songs_w1', 'total_secs_w1', 
    'num_100_w1', 'num_unq_w1', 'total_songs_w2', 'total_secs_w2', 
    'num_100_w2', 'num_unq_w2', 'total_songs_w3', 'total_secs_w3', 
    'num_100_w3', 'num_unq_w3', 'active_days_w0', 'active_days_w1', 
    'active_days_w2', 'active_days_w3', 'last_3d_raw_rows', 
    'coefficient_of_daily_variation_feb', 'max_single_day_songs_w0', 
    'hist_prior_2m_avg_songs', 'hist_prior_2m_avg_secs', 'hist_prior_2m_avg_days_active', 
    'hist_prior_2m_avg_unq', 'hist_prior_2m_avg_repeats', 'feb_songs_vs_prior_avg_delta', 
    'feb_secs_vs_prior_avg_delta', 'feb_active_days_vs_prior_avg_delta', 
    'feb_unq_vs_prior_avg_delta', 'feb_repeats_vs_prior_avg_delta', 'feb_vs_jan_songs_delta', 
    'feb_vs_jan_secs_delta', 'feb_vs_jan_active_days_delta', 'feb_vs_jan_unq_delta', 
    'feb_vs_jan_repeats_delta', 'jan_vs_dec_songs_delta', 'jan_vs_dec_secs_delta', 
    'jan_vs_dec_unq_delta', 'jan_vs_dec_repeats_delta', 'trend_3m_monthly_velocity_total_secs', 
    'trend_3m_monthly_velocity_num_unq', 'trend_3m_monthly_velocity_num_100', 
    'trend_3m_monthly_velocity_days_active', 'trend_3m_monthly_velocity_repeat_songs', 
    'songs_final_week_vs_prior_week_delta', 'secs_final_week_vs_prior_week_delta', 
    'completed_songs_final_week_vs_prior_week_delta', 'unique_songs_final_week_vs_prior_week_delta', 
    'avg_daily_songs_last_3d', 'avg_daily_secs_last_3d', 'songs_last_3d_vs_w0_daily_delta', 
    'secs_last_3d_vs_w0_daily_delta', 'last_3d_active_rate', 'last2wk_vs_last_month_numunq_avg_diff', 
    'feb_daily_session_density', 'feb_daily_variety_density', 'last_3d_micro_session_density', 
    'raw_last_3d_daily_songs', 'raw_w0_daily_songs', 'raw_last_3d_active_days', 
    'raw_w0_active_days', 'raw_feb_log_rows', 'feb_true_active_days', 
    'true_relative_performance_ratio_complete', 'active_day_engagement_density_feb', 
    'extreme_stream_compression_ratio_w0'
]

print("Applying literal absolute zero fills to all streaming dimensions...")
for col in user_log_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0.0)

print("\n--- STEP 2: THE MASTER COHORT SANITY AUDIT ---")
# Count total remaining nulls across the entire DataFrame matrix
total_remaining_nans = df.isna().sum().sum()

if total_remaining_nans == 0:
    print("=======================================================================")
    print("🎉 EXCELLENT WORK! THE MASTER FEATURE MATRIX IS NOW 100% CLEAN! 🎉")
    print(f"-> Total rows processed: {df.shape[0]:,}")
    print(f"-> Total features structured: {df.shape[1]:,}")
    print(f"-> Remaining NaNs across all columns: {total_remaining_nans}")
    print("=======================================================================")
else:
    print(f"⚠️ Warning: There are still {total_remaining_nans:,} unhandled NaNs remaining.")
    # Show exactly where they are hiding
    nan_summary = df.isna().sum()
    print(nan_summary[nan_summary > 0])

--- STEP 1: IDENTIFYING ALL REMAINING USER LOG COLUMNS ---
Applying literal absolute zero fills to all streaming dimensions...

--- STEP 2: THE MASTER COHORT SANITY AUDIT ---
=======================================================================
🎉 EXCELLENT WORK! THE MASTER FEATURE MATRIX IS NOW 100% CLEAN! 🎉
-> Total rows processed: 970,960
-> Total features structured: 160
-> Remaining NaNs across all columns: 0
=======================================================================

In [30]:
df.isna().sum()

msno                                              0
is_churn                                          0
city                                              0
bd                                                0
gender                                            0
registered_via                                    0
registration_init_time                            0
hist_ex_latest_mode_payment_plan_days             0
hist_ex_latest_mode_actual_amount_paid            0
hist_ex_latest_mode_plan_list_price               0
hist_ex_latest_mean_payment_plan_days             0
hist_ex_latest_mean_actual_amount_paid            0
hist_ex_latest_mean_plan_list_price               0
hist_ex_latest_mean_coverage_days                 0
hist_ex_latest_mean_discount_amount               0
hist_latest_payment_plan_days                     0
hist_latest_plan_list_price                       0
hist_latest_actual_amount_paid                    0
hist_latest_coverage_days                         0
hist_latest_is_cancel                             0
hist_latest_is_auto_renew                         0
hist_total_cancels                                0
hist_transaction_count                            0
hist_payment_method_change                        0
hist_tenure_days                                  0
hist_recency_days                                 0
hist_cancel_rate                                  0
payment_method_mode                               0
hist_ex_latest_mode_is_auto_renew                 0
recent_autorenew_intent_trend                     0
hist_expiration_recency_days                      0
payment_toggle_state_flips                        0
payment_elasticity_vector                         0
replenishment_consistency_variance                0
payment_discount_amount                           0
payment_discount_ratio                            0
is_promo_tier_subscriber                          0
hist_snap_dec_total_secs                          0
hist_snap_dec_num_25                              0
hist_snap_dec_num_50                              0
hist_snap_dec_num_75                              0
hist_snap_dec_num_985                             0
hist_snap_dec_num_100                             0
hist_snap_dec_num_unq                             0
hist_snap_dec_total_songs                         0
hist_snap_dec_days_active                         0
hist_snap_dec_repeat_songs                        0
hist_snap_jan_total_secs                          0
hist_snap_jan_num_25                              0
hist_snap_jan_num_50                              0
hist_snap_jan_num_75                              0
hist_snap_jan_num_985                             0
hist_snap_jan_num_100                             0
hist_snap_jan_num_unq                             0
hist_snap_jan_total_songs                         0
hist_snap_jan_days_active                         0
hist_snap_jan_repeat_songs                        0
jan_pre_w3_num_unq                                0
jan_pre_w3_days_active                            0
hist_snap_feb_total_secs                          0
hist_snap_feb_num_25                              0
hist_snap_feb_num_50                              0
hist_snap_feb_num_75                              0
hist_snap_feb_num_985                             0
hist_snap_feb_num_100                             0
hist_snap_feb_num_unq                             0
hist_snap_feb_total_songs                         0
hist_snap_feb_days_active                         0
hist_snap_feb_repeat_songs                        0
dec_raw_log_rows                                  0
jan_raw_log_rows                                  0
feb_raw_log_rows                                  0
total_songs_w0                                    0
total_secs_w0                                     0
num_100_w0                                        0
num_unq_w0                                        0
total_songs_w1                                    0
total_secs_w1                                     0
num_100_w1                                        0
num_unq_w1                                        0
total_songs_w2                                    0
total_secs_w2                                     0
num_100_w2                                        0
num_unq_w2                                        0
total_songs_w3                                    0
total_secs_w3                                     0
num_100_w3                                        0
num_unq_w3                                        0
active_days_w0                                    0
active_days_w1                                    0
active_days_w2                                    0
active_days_w3                                    0
last_3d_secs                                      0
last_3d_songs                                     0
last_3d_unq                                       0
last_3d_active_days                               0
last_3d_raw_rows                                  0
coefficient_of_daily_variation_feb                0
max_single_day_songs_w0                           0
inactivity_chunkiness_index_feb                   0
hist_prior_2m_avg_songs                           0
hist_prior_2m_avg_secs                            0
hist_prior_2m_avg_days_active                     0
hist_prior_2m_avg_unq                             0
hist_prior_2m_avg_repeats                         0
feb_songs_vs_prior_avg_delta                      0
feb_secs_vs_prior_avg_delta                       0
feb_active_days_vs_prior_avg_delta                0
feb_unq_vs_prior_avg_delta                        0
feb_repeats_vs_prior_avg_delta                    0
feb_vs_jan_songs_delta                            0
feb_vs_jan_secs_delta                             0
feb_vs_jan_active_days_delta                      0
feb_vs_jan_unq_delta                              0
feb_vs_jan_repeats_delta                          0
jan_vs_dec_songs_delta                            0
jan_vs_dec_secs_delta                             0
jan_vs_dec_unq_delta                              0
jan_vs_dec_repeats_delta                          0
trend_3m_monthly_velocity_total_secs              0
trend_3m_monthly_velocity_num_unq                 0
trend_3m_monthly_velocity_num_100                 0
trend_3m_monthly_velocity_days_active             0
trend_3m_monthly_velocity_repeat_songs            0
songs_final_week_vs_prior_week_delta              0
secs_final_week_vs_prior_week_delta               0
completed_songs_final_week_vs_prior_week_delta    0
unique_songs_final_week_vs_prior_week_delta       0
avg_daily_songs_last_3d                           0
avg_daily_secs_last_3d                            0
songs_last_3d_vs_w0_daily_delta                   0
secs_last_3d_vs_w0_daily_delta                    0
last_3d_active_rate                               0
last2wk_vs_last_month_numunq_avg_diff             0
feb_daily_session_density                         0
feb_daily_variety_density                         0
last_3d_micro_session_density                     0
raw_last_3d_daily_songs                           0
raw_w0_daily_songs                                0
raw_last_3d_active_days                           0
raw_w0_active_days                                0
raw_feb_log_rows                                  0
feb_true_active_days                              0
true_relative_performance_ratio_complete          0
active_day_engagement_density_feb                 0
extreme_stream_compression_ratio_w0               0
inter_auto_renew_x_fading_3d_stats                0
inter_auto_renew_x_last_3d_low_unq                0
inter_auto_renew_x_w0_structural_slump            0
inter_auto_renew_x_multi_window_decay             0
inter_auto_renew_x_engagement_desert              0
inter_auto_renew_x_promo_wall_cross               0
inter_auto_renew_x_ghost_billing_disconnect       0
inter_loyal_x_low_3d_unq                          0
inter_loyal_x_low_tier_payer                      0
inter_autorenew_x_desert_payer                    0
inter_autorenew_x_low_tier_payer                  0
is_legacy_ghost                                   0
ghost_group_base_rate                             0
time_active                                       0
dtype: int64